[workspace]
members = [
    "cosmic-panel-bin",
    "cosmic-panel-config"
]

[profile.release]
lto = "thin"

[patch."https://github.com/Smithay/client-toolkit"]
sctk = { git = "https://github.com/smithay/client-toolkit//", package = "smithay-client-toolkit" }
[patch."https://github.com/pop-os/xdg-shell-wrapper"]
# xdg-shell-wrapper-config = { git = "https://github.com/pop-os/xdg-shell-wrapper//", branch = "feat-security-context" }
# xdg-shell-wrapper = { git = "https://github.com/pop-os/xdg-shell-wrapper//", branch = "feat-security-context" }
[workspace.dependencies]
sctk = { git = "https://github.com/smithay/client-toolkit", package = "smithay-client-toolkit", features = ["calloop", "xkbcommon"] }
