[workspace]
members = [
    "cosmic-panel-bin",
    "cosmic-panel-config"
]

[profile.release]
lto = "thin"

[patch."https://github.com/Smithay/client-toolkit"]
sctk = { git = "https://github.com/smithay/client-toolkit//", package = "smithay-client-toolkit", features = ["calloop", "xkbcommon"] }
