[package]
name = "cosmic-panel-config"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["wayland-rs"]
wayland-rs = ["wayland-protocols-wlr", "xdg-shell-wrapper-config"]
[dependencies]
anyhow = "1.0.68"
ron = "0.8.0"
serde = { version = "1.0.152", features = ["derive"] }
tracing = "0.1.37"
wayland-protocols-wlr = { version = "0.1.0", features = ["server"], optional = true}
cosmic-config = { git = "https://github.com/pop-os/libcosmic",  tag = "cosmic-config-derive" }
# cosmic-config = { path = "../../libcosmic/cosmic-config/" }
# xdg-shell-wrapper-config = { path = "../../xdg-shell-wrapper/xdg-shell-wrapper-config", optional = true }
xdg-shell-wrapper-config = { git = "https://github.com/pop-os/xdg-shell-wrapper", optional = true, rev = "a5bf783" }

